apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-check-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitor-check-beta
  template:
    metadata:
      labels:
        app: monitor-check-beta
    spec:
      containers:
      - name: monitor-check-beta
        image: altershield/altershield-defender:monitor-check-beta-1.0.1
        ports:
        - containerPort: 8083
